name = "smart-time-manager-auth"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
FRONTEND_URL = "https://08106499.smart-time-manager.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "smart-time-manager-users"
database_id = "88a76946-94d0-4508-a91f-9dc9adf962a9"
